### ISSUE TITLE
error 403 (Forbidden)

### ISSUE THREAD

**Issue by nemson-source** [KichangKim/DanbooruDownloader#13]
hi
i'm receiving an error 403 sins today and i can't figure out why

this is the complet error

2023-02-06 00:42:00.1797|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-02-06 00:42:00.4405|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\DanbooruDownloader-master\DanbooruDownloader-master\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\DanbooruDownloader-master\DanbooruDownloader-master\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\DanbooruDownloader-master\DanbooruDownloader-master\DanbooruDownloader\Utilities\TaskUtility.cs:line 16

**Comment by nemson-source** [comment]
for others read this
https://github.com/KichangKim/DanbooruDownloader/issues/11

**Comment by nemson-source** [comment]
i found that i need to install CloudflareSolverRe but i cant get it to install

**Comment by nemson-source** [comment]
Okay, I found the solution. For others who have the same problem, this is how to solve it:

for other that have the same problem this is how you solve the problem
Install the uncompiled version of DanbooruDownloader by clicking the green button named 'Code' and selecting 'Download ZIP'.

2. Open Visual Studio Code and go to the file '/Utilities/DanbooruUtility.cs' and replace this:

```
public static async Task<JObject[]> GetPosts(long startId, string username, string apikey)
        {
            using (HttpClient client = new HttpClient())
            {
                string url = GetPostsUrl(startId, username, apikey);
                string jsonString = await client.GetStringAsync(url);

                JArray jsonArray = JArray.Parse(jsonString);

                return jsonArray.Cast<JObject>().ToArray();
            }
        }
```

to this:

```
public static async Task<JObject[]> GetPosts(long startId, string username, string apikey)
        {
            string url = GetPostsUrl(startId, username, apikey);
            var target = new Uri(url);
            var handler = new ClearanceHandler
            {
                MaxTries = 3,
                ClearanceDelay = 3000
            };

            using (HttpClient client = new HttpClient(handler))
            {
                string jsonString = await client.GetStringAsync(target);

                JArray jsonArray = JArray.Parse(jsonString);

                return jsonArray.Cast<JObject>().ToArray();
            }
        }
```

and don't forget to include ```using CloudflareSolverRe;``` at the top of the file.

4. go to the file /Commands/DumpCommands.cs

then replace this:

```
static async Task Download(string uri, string path)
        {
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(uri, HttpCompletionOption.ResponseHeadersRead);

                switch (response.StatusCode)
                {
                    case HttpStatusCode.Forbidden:
                    case HttpStatusCode.NotFound:
                        throw new NotRetryableException();
                }

                response.EnsureSuccessStatusCode();

                using (FileStream fileStream = File.Create(path))
                {
                    using (Stream httpStream = await response.Content.ReadAsStreamAsync())
                    {
                        httpStream.CopyTo(fileStream);
                        fileStream.Flush();
                    }
                }
            }
        }
```

with this

```
static async Task Download(string uri, string path)
        {
            var handler = new ClearanceHandler
            {
                MaxTries = 3,
                ClearanceDelay = 3000
            };

            using (HttpClient client = new HttpClient(handler))
            {
                HttpResponseMessage response = await client.GetAsync(uri, HttpCompletionOption.ResponseHeadersRead);

                switch (response.StatusCode)
                {
                    case HttpStatusCode.Forbidden:
                    case HttpStatusCode.NotFound:
                        throw new NotRetryableException();
                }

                response.EnsureSuccessStatusCode();

                using (FileStream fileStream = File.Create(path))
                {
                    using (Stream httpStream = await response.Content.ReadAsStreamAsync())
                    {
                        httpStream.CopyTo(fileStream);
                        fileStream.Flush();
                    }
                }
            }
        }
```

and don't forget to include ```using CloudflareSolverRe;``` at the top of the file.

5. Ensure that you have the NuGet Package Manager GUI extension installed.
6. Open the GUI by opening the Command Palette (Ctrl+Shift+P) and selecting 'NuGet Package Manager GUI'.
7. Click on 'Install Package' and search for 'CloudflareSolverRe.Captcha' and install it.
8. When installed, a pop-up should appear that says 'Restore', click on it.
9. Then, go to the file '/DanbooruDownloader.sln' and start the build by pressing Ctrl + Shift + B or navigating to Terminal > Run Build Task.
10. When the build is complete, you can find it in the bin folder and use the 'DanbooruDownloader.exe'.
