### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by snaeker58** [KichangKim/DanbooruDownloader#17]
My command: .\DanbooruDownloader.exe dump MyDataset --username ************ --api-key *********************

**Log:**
```
2023-06-16 17:49:51.7826|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:49:51.9206|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:49:54.9340|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:49:55.0212|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:49:58.0268|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:49:58.0767|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:50:01.0918|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:50:01.1784|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:50:04.1982|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:50:04.2422|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:50:07.2687|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:50:07.3574|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:50:10.3668|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:50:10.4347|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:50:13.4421|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:50:13.4887|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:50:16.4969|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:50:16.5789|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:50:19.5882|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:50:19.6706|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:50:22.6785|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:50:22.7251|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:53:11.0371|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:53:11.2264|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:53:14.2476|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:53:14.3370|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:53:17.3477|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:53:17.4175|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:53:20.4249|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:53:20.4696|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
2023-06-16 17:53:23.4822|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2023-06-16 17:53:23.5674|ERROR|DanbooruDownloader.Commands.DumpCommand|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DanbooruDownloader.Utilities.DanbooruUtility.GetPosts(Int64 startId, String username, String apikey) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\DanbooruUtility.cs:line 26
   at DanbooruDownloader.Commands.DumpCommand.<>c__DisplayClass1_1.<<Run>b__0>d.MoveNext() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 49
--- End of stack trace from previous location ---
   at DanbooruDownloader.Utilities.TaskUtility.RunWithRetry(Func`1 job, Func`2 retryCondition, Int32 retryCount, Int32 retryDelay) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Utilities\TaskUtility.cs:line 16
```

**Comment by nemson-source** [comment]
hi
this should help
https://github.com/KichangKim/DanbooruDownloader/issues/13
