### ISSUE TITLE
App can`t start

### ISSUE THREAD

**Issue by ka1tzyu** [KichangKim/DanbooruDownloader#4]
When I write `DanbooruDownloader dump MyDataset` I see it:
```
2020-08-25 21:19:31.9651|INFO|DanbooruDownloader.Commands.DumpCommand|Downloading metadata ... (1 ~ )
2020-08-25 21:19:33.3554|INFO|DanbooruDownloader.Commands.DumpCommand|Checking 200 posts ...
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DanbooruDownloader.Commands.DumpCommand.ConvertToPost(JObject jsonObject) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 240
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DanbooruDownloader.Commands.DumpCommand.Run(String path, Int64 startId, Boolean ignoreHashCheck, Boolean includeDeleted) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 66
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at DanbooruDownloader.Program.<>c__DisplayClass0_1.<Main>b__2() in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Program.cs:line 46
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DanbooruDownloader.Program.Main(String[] args) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Program.cs:line 59
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at DanbooruDownloader.Commands.DumpCommand.ConvertToPost(JObject jsonObject) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 240
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DanbooruDownloader.Commands.DumpCommand.Run(String path, Int64 startId, Boolean ignoreHashCheck, Boolean includeDeleted) in D:\Projects\Machine Learning Projects\DanbooruDownloader\DanbooruDownloader\Commands\DumpCommand.cs:line 66<--
```

**Comment by masnn** [comment]
The same.

**Comment by evanjs** [comment]
Seems to work fine if built from source.
I used .NET Core 3.1 to compile the application, as 2.2.0 has reached [end of life status](https://dotnet.microsoft.com/download/dotnet-core/2.2).

**Comment by hackwellfox** [comment]
the same

**Comment by RyouMon** [comment]
Release files is not up to date.

**Comment by ka1tzyu** [comment]
I'm closing the issue because project's abandoned

**Comment by HijackHornet** [comment]
Even if projects abandonned, you shouldnt close the issue.

**Comment by ka1tzyu** [comment]
> Even if projects abandonned, you shouldnt close the issue.

Developer will not fix it. This error will not be fixed even somebody does pull request.

**Comment by HijackHornet** [comment]
Yes but that would help new people see that the project is abandonned if there is lots of issue opened for years. 
Else it looks like its working just fine.

**Comment by HijackHornet** [comment]
Also, i just downloaded and compiled the project and it works correctly. Only the release is outdated

**Comment by MarisaCodes** [comment]
I compiled it but it keeps exiting whenever I run it. How do I fix it? I never worked with .NET before

**Comment by ghost** [comment]
Sorry its been too long i have no idea how to help :/

**Comment by nemson-source** [comment]
what is the error you are getting @MarisaCodes ?
